// src/constants/columns.js

export const EXPORT_COLUMNS = {
  server: {
    device_label: "Device / Label",
    model: "Model",
    status: "Status",
    rack_no: "Rack No.",
    new_rack_no: "New Rack No.",
    server_owner_dept: "Server Owner Dept.",
    server_admin_name: "Server Admin Name",
    serial_number: "Serial Number",
    uba_tag_number: "UBA Tag Number",
    deployment_date: "Deployment Date",
  },
  power: {
    device_name: "Device Name",
    device_type: "Device Type",
    device_model: "Device Model",
    device_location: "Location",
    operational_status: "Operational Status",
    condition_status: "Condition Status",
    serial_number: "Serial Number",
    uba_tag: "UBA Tag",
  },
  cooling: {
    device_name: "Device Name",
    device_type: "Device Type",
    device_model: "Model",
    device_location: "Location",
    year_procured: "Year Procured",
    year_installed: "Year Installed",
    status: "Status",
    serial_number: "Serial Number",
    uba_tag: "UBA Tag",
    remarks: "Remarks",
  },
};
export const TABLE_MAPS = {
  server: "dc_inventory",
  power: "power_devices",
  cooling: "cooling_devices",
};

export const IMPORT_COLUMNS = {
  server: {
    "Device / Label": "device_label",
    Model: "model",
    Status: "status",
    "Rack No.": "rack_no",
    "New Rack No.": "new_rack_no",
    "Server Owner Department": "server_owner_dept",
    "Admin Name": "server_admin_name",
    "Serial Number": "serial_number",
    "UBA Tag Number": "uba_tag_number",
    "Deployment Date": "deployment_date",
  },
  power: {
    "Device Name": "device_name",
    "Device Type": "device_type",
    "Device Model": "device_model",
    Location: "device_location",
    "Operational Status": "operational_status",
    "Condition Status": "condition_status",
    "Serial Number": "serial_number",
    "UBA Tag": "uba_tag",
  },
  cooling: {
    "Device Name": "device_name",
    "Device Type": "device_type",
    Model: "device_model",
    Location: "device_location",
    "Year Procured": "year_procured",
    "Year Installed": "year_installed",
    Status: "status",
    "Serial Number": "serial_number",
    "UBA Tag": "uba_tag",
    Remarks: "remarks",
  },
};
